on:
  push:
  workflow_dispatch:

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
